baseURL = 'https://www.cironet.eu/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'cironet data security | bitcoin and lightning'
  metaDescription = "code is law"

# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[Languages.de]
languageName = "de"
languageCode = "de-de"
contentDir = "content/de"
weight = 2
mark = "de"

[Languages.se]
languageName = "se"
languageCode = "se-se"
contentDir = "content/se"
weight = 3
mark = "se"

[Languages.fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 4
mark = "FR"

[taxonomies]
  category= "theme"
  scene = "scenes"
